---
jobs:
- name: build
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: project
      resource: docker-nuxeo
      trigger: true
    - get: version
      params: {pre: rc}
  - put: version
    params: {file: version/version}
  - put: identifix-docker-repo
    params:
      build: project
      dockerfile: project/9.2/Dockerfile
      tag: version/version
      tag_as_latest: false

- name: shipit
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: project
      resource: docker-nuxeo
      passed: [build]
    - get: identifix-docker-repo
      passed: [build]
      params: {save: true}
    - get: version
      passed: [build]
      params: {bump: final}
  - put: version
    params: {file: version/version}
  - put: identifix-docker-repo
    params:
      load: identifix-docker-repo
      dockerfile: project/9.2/Dockerfile
      tag: version/version
      tag_as_latest: true

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/version}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/version}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [build]
    params: {bump: patch, pre: rc}
    trigger: true
  - put: version
    params: {file: version/version}

resources:
- name: docker-nuxeo
  type: git
  source:
    uri: git@github.com:Identifix/docker-nuxeo.git
    private_key: ((data-ssh))
    ignore_paths:
    - LICENSE
    - NOTICE.md
    - pipeline.yml
    - README.md

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: git@github.com:Identifix/docker-nuxeo.git
    branch: version
    file: version
    private_key: ((data-ssh))

- name: identifix-docker-repo
  type: docker-image
  source:
    repository: ((nuxeo-studio-resource.docker_registry_repo))
    username: ((nuxeo-studio-resource.docker_registry_user))
    password: ((nuxeo-studio-resource.docker_registry_password))

